### ISSUE TITLE
Try using R's compiler for speed increases

### ISSUE THREAD

**Issue by aoliver44** [aoliver44/taxaHFE#68]
Random thought - try running the tree.r functions through the compiler package in r. See if we get any performance improvements.

**Comment by mmmckay** [comment]
did some digging on this and I _think_ it's enable by default in R versions > 3.4, so calling `cmpfun` would be redundant. I'm not 100% positive this is correct but the links below lead me to believe it

https://jtr13.github.io/cc20/speed-up-in-r-programming.html#:~:text=Since%20R%203.4.0%20(Apr%202017)%2C%20the%20JIT%20(%E2%80%98Just%20In%20Time%E2%80%99)%20bytecode%20compiler%20is%20enabled%20by%20default%20at%20its%20level%203.

https://www.rdocumentation.org/packages/compiler/versions/3.6.2/topics/compile#:~:text=is%20going%20on.-,enableJIT,-enables%20or%20disables

https://stackoverflow.com/questions/41502721/could-someone-explain-what-compiling-in-r-is-and-why-it-would-speed-up-this-c

**Comment by aoliver44** [comment]
Wow i didnt know this. Those links made sense to me. I'll close this issue, were probs not going to get a boost here. I suppose once we've done everything we wanted to do (ie logging), we can profile the functions again and see if there are any obvious improvements we can make.

Thanks for looking into this.
